from .bonsai_nodes import (
    NODE_CLASS_MAPPINGS as BONSAI_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BONSAI_NODE_DISPLAY_NAME_MAPPINGS,
)
from .pintu_nodes import (
    NODE_CLASS_MAPPINGS as PINTU_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PINTU_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **BONSAI_NODE_CLASS_MAPPINGS,
    **PINTU_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **BONSAI_NODE_DISPLAY_NAME_MAPPINGS,
    **PINTU_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
