from .color_panel import (
    NODE_CLASS_MAPPINGS as COLOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COLOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_crop import (
    NODE_CLASS_MAPPINGS as CROP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CROP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_standardizer import (
    NODE_CLASS_MAPPINGS as STANDARDIZER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STANDARDIZER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .pintu_nodes import (
    NODE_CLASS_MAPPINGS as PINTU_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PINTU_NODE_DISPLAY_NAME_MAPPINGS,
)
from .depth_control import (
    NODE_CLASS_MAPPINGS as DEPTH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DEPTH_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lighting_prompt_selector import (
    NODE_CLASS_MAPPINGS as LIGHTING_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LIGHTING_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **COLOR_NODE_CLASS_MAPPINGS,
    **CROP_NODE_CLASS_MAPPINGS,
    **STANDARDIZER_NODE_CLASS_MAPPINGS,
    **PINTU_NODE_CLASS_MAPPINGS,
    **DEPTH_NODE_CLASS_MAPPINGS,
    **LIGHTING_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **COLOR_NODE_DISPLAY_NAME_MAPPINGS,
    **CROP_NODE_DISPLAY_NAME_MAPPINGS,
    **STANDARDIZER_NODE_DISPLAY_NAME_MAPPINGS,
    **PINTU_NODE_DISPLAY_NAME_MAPPINGS,
    **DEPTH_NODE_DISPLAY_NAME_MAPPINGS,
    **LIGHTING_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
